# Generated by Django 3.1.5 on 2021-02-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_word', models.CharField(max_length=20)),
                ('second_word', models.CharField(max_length=20)),
                ('distance', models.FloatField()),
                ('minor_level', models.IntegerField()),
            ],
        ),
    ]
